.github/workflows/main-deploy.yml

[Deploy] 배포 자동화 테스트

---

.github/workflows/main-deploy.yml

배포 자동화 테스트

---

package.json
src/App.tsx
src/apis/member.ts
src/components/Common/Header/ProfileDropdown/index.tsx
src/components/Common/Header/index.tsx
src/components/Modal/LoginModal/index.tsx
src/pages/HomePage/index.tsx
src/pages/OAuthRedirectPage/index.tsx
src/routes/PrivateRoute.tsx
src/routes/Router.tsx
src/stores/user.ts
src/types/member.ts
src/utils/constants.ts
src/utils/fetch.ts
tsconfig.paths.json
yarn.lock

[Feat#31] 로그인 기능 구현

---

src/routes/PrivateRoute.tsx

[Fix#33] 로그인 private route오류 해결

---

src/apis/member.ts
src/apis/ticket.ts
src/components/Editor/DragDrop/index.tsx
src/components/Editor/DragDrop/style.ts
src/components/Editor/EditorFrame/index.tsx
src/components/Editor/Loading/index.tsx
src/components/Editor/Loading/style.ts
src/components/TicketList/index.tsx
src/pages/Editor/EditPage.tsx
src/pages/Editor/NewPage.tsx
src/pages/RegisterPage.tsx
src/routes/Router.tsx
src/templates/Editor/EditTemplate/index.tsx
src/templates/Editor/EditTemplate/style.ts
src/templates/Editor/NewTemplate/index.tsx
src/templates/Editor/NewTemplate/style.ts
src/templates/PostTemplate/index.tsx
src/types/member.ts
src/types/ticket.ts
src/utils/fetch.ts

[Feat#45] 회원가입 중복 아이디 처리, 사진 Drag & Drop 업로드, OCR 서버 연동

---

src/components/TicketbookList/TicketbookExample/index.tsx
src/components/TicketbookList/index.tsx
src/components/TicketbookList/style.ts
src/templates/HomeTemplate/index.tsx
src/types/ticket.ts

[Feat#55]  티켓홈 티켓북 개수 적을 시 UI 오류

---

src/apis/ticket.ts
src/apis/ticketbook.ts
src/components/Common/BasicButton/index.tsx
src/pages/Editor/EditPage.tsx
src/pages/Editor/NewPage.tsx
src/pages/WritePage.tsx
src/templates/WriteTemplate/index.tsx
src/templates/WriteTemplate/style.ts
src/types/ticket.ts
src/types/ticketbook.ts

[Feat#51] 글쓰기 티켓북 설정 구현, 글쓰기 API 연동

---

src/apis/ticket.ts
src/pages/PostPage.tsx
src/pages/WritePage.tsx
src/templates/PostTemplate/index.tsx
src/templates/WriteTemplate/index.tsx
src/types/ticket.ts

[Feat#63] 글 삭제, 수정

---

package.json
src/App.tsx
src/pages/Editor/EditPage.tsx
src/pages/WritePage.tsx
yarn.lock

[Feat#65] 글쓰기 Validation

---

src/components/ProfileEditor/index.tsx
src/components/ProfileEditor/style.ts
src/pages/ProfilePage.tsx
src/templates/ProfileTemplate/index.tsx

[Feat#56] 프로필 수정 코드 리팩토링, 조건 추가

---

src/components/Common/Profile/ProfileBox/style.ts
src/components/ProfileEditor/style.ts
src/pages/ProfilePage.tsx
src/templates/HomeTemplate/style.ts
src/templates/ProfileTemplate/style.ts

반응형 UI 수정
바이오 Input 높이 수정
프로필 수정 페이지 오류 해결

[Feat#56] 프로필 수정 페이지 오류 해결

---

src/templates/ErrorTemplate/index.tsx
src/templates/ErrorTemplate/style.ts

[Feat#57] 404 페이지 헤더 삭제

---

src/components/Common/Profile/ProfileBox/style.ts

[Feat#56] 화면 작을 시 바이오 줄바꿈 삭제

---

src/components/Editor/SideMenu/TextMenu/index.tsx
src/components/Editor/SideMenu/TextMenu/style.ts
src/components/Editor/SideMenu/index.tsx
src/pages/Editor/NewPage.tsx
src/pages/HomePage.tsx
src/stores/editor.ts
src/templates/Editor/EditTemplate/index.tsx
src/templates/Editor/EditTemplate/style.ts

[Feat#79] 템플릿 글자색 변경 & 홈 화면 오류 수정

---

src/pages/HomePage.tsx
src/pages/PostPage.tsx

[Feat#82] 올바르지 않은 주소, 비로그인 처리

---

package.json
src/components/Common/Header/ProfileDropdown/index.tsx
src/components/Common/Profile/ProfileBox/index.tsx
src/components/Editor/EditorFrame/index.tsx
src/components/SearchBox/index.tsx
src/components/TicketList/index.tsx
src/pages/WritePage.tsx
src/routes/Router.tsx
src/templates/PostTemplate/index.tsx
yarn.lock

[Fix#91] 라우터 path 오류 해결 및 자잘한 수정

---

src/components/Ticketbook/TicketbookSlider/index.tsx
src/components/Ticketbook/TicketbookSlider/style.ts

[Feat#90] 티켓북 슬라이드 반응형 구현

---

src/components/Editor/SideMenu/TicketInfoMenu/index.tsx
src/pages/Editor/EditPage.tsx

[Fix#103] 버그 처리

---

src/apis/ticket.ts
src/pages/MainPage.tsx

[Feat#109] 피드 기능 구현

---

package.json
src/components/TextEditor/index.tsx
src/pages/TicketbookPage.tsx
src/pages/WritePage.tsx
src/utils/image.ts
yarn.lock

[Feat#115] 이미지 압축

---

src/components/Common/TicketInfoBox/index.tsx
src/components/Common/TicketInfoBox/style.ts
src/pages/SearchPage.tsx
src/utils/string.ts

[Feat#122] 검색 이동 기능 구현
